### ISSUE TITLE
[BE] status가 매번 전송되는 문제.

### ISSUE THREAD

**Issue by evelon** [Trapscendence/ft_transcendence#144]
status 새 창을 켤 때마다 ONLINE이 됩니다. 이건 그냥 놔둬도 되지만 창을 하나씩 끄면 OFFLINE이 전송됩니다.
전에 했던 Map<string어쩌구Set<string>> 구조로 하면 해결될 거 같은데 변경해도 될까요?
@SeheonYu

**Comment by SeheonYu** [comment]
다른 창에서 로그인하면 기존 창에서 로그아웃되도록 수정하려했는데 단순히 세션만 만료시킨거라 적용이 잘 안됐나보네요.

우선 여러 창에서 로그인하는건 막아야 한다고 생각하고, 새로운 로그인 시도가 발생했을 때 기존 로그인을 만료시키던 새 로그인을 막던 해야할 것 같아요
