### ISSUE TITLE
[CM] 현재 develop에서 발생하는 이슈들

### ISSUE THREAD

**Issue by moon9ua** [Trapscendence/ft_transcendence#152]
develop 브랜치, 그리고 이를 따온 feature/common_gmoon 브랜치에서 제가 느낀 이슈들입니다.

- [x] #157
- [x] #158
- [x] #163
- [x] #164
- [x] #159
- [x] #162

**Comment by seohee-choi** [comment]
[CM] 로그아웃 버튼이 동작을 안합니다.
