### ISSUE TITLE
[Storage/BE] axios post 요청을 보낼 때 403 Forbidden 에러가 뜨는 현상

### ISSUE THREAD

**Issue by evelon** [Trapscendence/ft_transcendence#155]
amazing_picture.service
![image](https://user-images.githubusercontent.com/3518710/144050080-30f12189-96e2-41a7-98c3-32823ba53e5b.png)

storage의 app.controller
![image](https://user-images.githubusercontent.com/3518710/144050290-a74594f1-0766-4c70-9ff2-26769b876ff3.png)

storage의 app.module
![image](https://user-images.githubusercontent.com/3518710/144050399-366ae277-50e3-40d5-b823-3ddf4b3e53d2.png)

upload시 오류가 납니다.

**Comment by SeheonYu** [comment]
세션가드가 걸려서 그런거같아요

**Comment by evelon** [comment]
seyu님이 보낸 요청이랑 제 요청이랑 뭐가 다른걸까요. 🥵  sessionguard를 빼지는 않고 싶은데...

**Comment by SeheonYu** [comment]
제가 보낸 Delete에는 세션 가드가 없어요 upload 말고 다른 라우트 만들면 외부에서 접근 못하니까 가드 빼도 되지 않을까요

**Comment by SeheonYu** [comment]
스토리지 서비스를 프로필이랑 어매이징픽쳐 모듈 두개로 나눌까요?
