### ISSUE TITLE
[Channel] Channel 구현 체크리스트

### ISSUE THREAD

**Issue by moon9ua** [Trapscendence/ft_transcendence#24]
# BE
- [x] resolver, service 임시 구현 (~10/31)
- [x] user 에 channel field 추가
- [ ] 유저 권한에 따라 kick, ban, mute 가능 여부 설정
- [ ] 사이트 관리자는 owner 권한 가지도록 수정
- [ ] owner 양도 기능
- [x] 채널 들어가기 기능
- [x] 채널 떠나기 기능
- [ ] owner 자동 양도
- [ ] 마지막 유저가 떠나면 방 삭제
- [ ] admin 권한 부여 기능
- [ ] 친구 초대 기능(?)

# FE

### 전체적인 계획
- ChannelList 페이지: 컴포넌트화 (11/1)
- ChannelListContents 컴포넌트: gql 연결 (11/2)
- ChannelCreateModal 컴포넌트: 목업 구현 (11/3)
- ChannelCreateModal 컴포넌트: gql 연결 (11/3)
- Channel 페이지: 컴포넌트화 (11/4)
- Chatting 컴포넌트: subscription 공부 및 gql 연결 (11/4~11/5)
- Channel & ChannelList 페이지: 중요 동작 구현 및 스타일링 개선 및 컴포넌트 구체화 (11/6~11/7)
- Channel & ChannelList 페이지: 세부 동작 구현 (11/9~)
    - [x] Chatting 컴포넌트: 채팅창 스크롤 맨 아래로 고정하기
    - [x] Channel 스타일 개선
    - [x] 엔터 입력 시 채팅 전송
    - [x] ban, mute, block 등을 위한 NicknameMenu 개선
    - [x] mute gql 연결 및 mute된 사람의 input 막기
    - [x] channel_role에 따라 NicknameMenu 다르게 뜨도록 구현
    - [x] enter 구현
    - [ ] 차단(blackliist) 구현 #39 
    - [x] 방 들어갔을 때 mute, ban 정보 가져오기 #38 
- Channel & ChannelList 페이지: 추가 기능 구현 및 리팩토링 (11/12~)
    - [ ] 랜덤 방 들어가는 기능...은 백엔드에서? 프론트에서도 구현 가능할 것 같긴 한데
    - [ ] private, public 필터 기능

### 프론트적 이슈
- [ ] common: General Theme Color 바꿔보기
- [x] 스크롤을 SocialDrawer 안쪽으로 옮기기
- [x] UserSummary 컴포넌트: 폭 변경하거나 아예 개선하기 -> UserSuammry는 그대로 두고, 사용할 때 <Box>로 감싸 `display: inline-block` 옵션을 주었음
- [ ] ParticipantsList: 참가자 많아지면 어떻게 되는지 확인 안함
- [ ] 네비게이션 바에서 refetch 되게 수정해야... 또한 새로고침 했을 때 네비게이션 바가 제대로 위치하게 수정해야.
- [ ] Channel 컴포넌트들 height 개선 필요
- [ ] mute 알림 Alert에서 Snackbar로 교체 시도
- [ ] currentChannelId 캐시로 저장해서 깜빡임(로딩) 개선

### 백엔드적 이슈
- in, out을 subscription으로 하는데 만약 publish를 클라이언트가 못받는 경우엔?
    아니면 주기적으로 participants를 쿼리로 받아와야할까?
- [x] Channel 페이지: chat 입력시 subscription이 두번 오는 이슈 -> subscribeData에 대한 useEffect로 임시 해결
- [x] enterChannel 백엔드 에러: "null value in column \"channel_role\" of relation \"channel_user\" violates not-null constraint"
- [x] 이미 mute된 참가자에게 다시 mute를 걸면? -> mute 안되게 하기로...
- [x] 새로고침 시 mute에 대한 프론트 캐싱이 없어짐. 백엔드에서 새로 정보를 줘야 하는데... 어떻게? -> Channel에 mute, ban 등에 대한 필드 사용
- [x] mute 시 가끔 뜨는 `Unhandled Rejection (Error): Cannot read properties of undefined (reading 'add')` 에러는 뭘까? 새로고침 후에 다시 와서 해보면 된다... 뭐지? -> 백엔드의 mutedUser 클래스의 add 함수의 문제였어서 수정 완료
- channel_role과 site_role을 UserRole enum으로 둘 다 커버하는 듯?

**Comment by evelon** [comment]
- [ ] 유저 권한에 따라 kick, ban, mute 가능 여부 설정
- [ ] 사이트 관리자는 owner 권한 가지도록 수정
- [ ] owner 양도 기능
- [ ] 채널 들어가기 기능
- [ ] 채널 떠나기 기능
- owner 자동 양도
- 마지막 유저가 떠나면 방 삭제
- [ ] 친구 초대 기능?

**Comment by moon9ua** [comment]
위키로 옮길까 생각중입니다... (이슈는 세부적인 것들로 작성해야할 것 같아서)
위키가 별로면 재오픈하도록 하겠습니다. 이슈 닫습니다.
