### ISSUE TITLE
[CM] migration network 설정

### ISSUE THREAD

**Issue by SeheonYu** [Trapscendence/ft_transcendence#29]
docker-compose 에 migration 서비스 네트워크가 설정 안돼있어요!

**Comment by SeheonYu** [comment]
frontend랑 backend 말고 다른 서비스 포트는 막아두는게 좋을 것 같아요

**Comment by moon9ua** [comment]
| docker-compose 에 migration 서비스 네트워크가 설정 안돼있어요!

그런데 `networks: default` 여서 쓰나 안쓰나 다 똑같은건줄 알았는데, 혹시 이에 대해 아시는 분 계신가요?

**Comment by SeheonYu** [comment]
안쓰면 `default` 말고 다른 네트워크로 묶이는거같아요

database만 default 네트워크에 두고 migration만 네트워크 설정을 안하면 migration에서 db에 접근못하고
database랑 migration 둘 다 network 설정을 안하면 migration에서 db로 접근해요
