### ISSUE TITLE
[DM]클라이언트가 DM으로 최근 메시지들을 받아오려 할 때, 전체 메시지의 갯수를 알아야 하는 이슈

### ISSUE THREAD

**Issue by seohee-choi** [Trapscendence/ft_transcendence#30]
- DM+ offset값 지정으로 최근의 메시지 n개만 받아오려고 하는 경우
- 현재 offset은 메시지가 앞에서부터 몇번째 메시지인지 계산해야하고 해당 수를 지정해줘야하기때문에 
- 클라이언트가 DM으로 사용자외의 최근 DM을 받아오려 할 때, 해당 유저와 주고받은 모든 message 수를 알아야 합니다.
- 이부분에 대해서 백엔드에서 최신 DM만+오래된순서대로(순서는 지금 그대로면 됨) 로 보내주실 수 있을까요?

**Comment by seohee-choi** [comment]
메시지가 '1', '2', '3', '4', '5', '6', '7' 이 있다고 가정할 때

`DM(){… messages (limit:10, offset:3)}`

쿼리를 이렇게 보내는 경우

최신 3개의 DM인 5, 6, 7이 오는 게 아닌

앞에서 3개를 뺀 1, 2, 3을 제외한 4, 5, 6, 7이 반환되는데요.

이 경우 Dm이 500개라고 가정할 때 최신의 3개를 가져오고 싶으면 클라이언트가 497이라는 수를 알고 있어야 합니다.

이 숫자를 알고 있는것이 비효율적이라고 생각해서,  offset을 3으로 지정하면 최신의 3개만(정렬순서는 현재와 같이) 받아오도록 처리해주실 수 있을까요?

제가 생각한 방식이 비효율적이거나 이치에 맞지 않다면 말씀해주세요?

**Comment by evelon** [comment]
확인했습니다 조치하겠습니다

**Comment by evelon** [comment]
커밋에 번호를 안 달았네요... 확인하고 닫아주시기 바랍니다.
