### ISSUE TITLE
[CM] docker-compose environment 오타

### ISSUE THREAD

**Issue by SeheonYu** [Trapscendence/ft_transcendence#43]
도커컴포즈 `frontend` 서비스 환경변수 `REACT_APP_BACKEND_POST` -> `REACT_APP_BACKEND_PORT`

**Comment by moon9ua** [comment]
seyu님께서 수정하셨으니 이슈 닫겠습니다!

**Comment by SeheonYu** [comment]
푸시됐나요??

**Comment by moon9ua** [comment]
네 feature/channel (그나마 제일 최근 일들은 여기 브랜치에서 하는 것 같아서..) 에는 push되어있는데, 아마 develop 브랜치로 합쳐야 될 것 같긴 합니다

**Comment by SeheonYu** [comment]
아하 커밋할때 이슈번호 붙여주시면 확인하기 편할거같아요
