### ISSUE TITLE
[Login] GqlSessionGuard에서 undefined context.req

### ISSUE THREAD

**Issue by SeheonYu** [Trapscendence/ft_transcendence#44]
`GqlExecutionContext.create(context).getContext() => {}`

**Comment by moon9ua** [comment]
fc37af4 브랜치에서 임시조치 했습니다.
제대로 고치려면 `WebSocketLink`, `createHttpLink`, `ApolloClient`, `from`에 대한 공부가 필요할 것 같습니다...
