### ISSUE TITLE
[Docker] node 버전이 lts가 아님

### ISSUE THREAD

**Issue by evelon** [Trapscendence/ft_transcendence#46]
안정화 버전은 훨씬 밑이고 현재 저희가 쓰는 버전은 더 최신 버전이라고 합니다.

**Comment by evelon** [comment]
일단 feature/channel에서 해결함.

**Comment by moon9ua** [comment]
> `FROM node:16-alpine3.12

이렇게 해결된 것 같으니 이슈 닫습니다!
