### ISSUE TITLE
[FE] 전체 구조 리팩토링에 대한 고민

### ISSUE THREAD

**Issue by moon9ua** [Trapscendence/ft_transcendence#53]
1. routes 폴더가 필요할까? 괜히 prop drilling만 생길 것 같아서... 삭제하는 것이 나을 것 같다.
2. utils에 있는 gql 관련 파일들을 분리하고 싶다. gqls 등의 폴더로 옮기고자 함.
3. gql문을 여러개 묶을 수 있는 것을 바탕으로 상위 컴포넌트에서 한번에 gql query를 실행하는 식으로 리팩토링 하는게 낫지 않을까

위와 같은 고민들을 하고있는데 1, 2번 리팩토링하려면 다른 분들의 동의가 필요할 것 같습니다. 👀

**Comment by SeheonYu** [comment]
> routes 폴더가 필요할까? 괜히 prop drilling만 생길 것 같아서... 삭제하는 것이 나을 것 같다.

routes 폴더를 삭제하고 안에 페이지 디렉토리를 src 하위로 옮기는건 좋은 것 같아요. 루트에 App.tsx가 있고 공용으로 사용하는 컴포넌트들은 common에 넣고 나머지 라우터들을 쭉 나열하는게 백엔드랑 구조가 비슷해서 좋을 것 같아요

> utils에 있는 gql 관련 파일들을 분리하고 싶다. gqls 등의 폴더로 옮기고자 함.

gql 내용이 너무 길어져서 분리하는건 좋은 생각 같은데, gql을 라우트마다 하나씩 놓고 사용하는건 어떤가요

**Comment by moon9ua** [comment]
* 저는 개인적으로 폴더구조를 src/components만 남기고 routes를 삭제하는 방향이 어떨까 생각하긴 했습니다
* gql을 컴포넌트 폴더? 라우트 폴더? 마다 놓고 사용하는거... 원래 제가 그렇게 했었는데, 여러 컴포넌트에서 공용으로 쓰는 것들이 생겨서 그냥 한군데서 관리하는게 편하긴 하더라고요. 일단 지금 utils 폴더에 이것저것 있는데 이걸 따로 폴더를 만들어서 분리하고 싶어요.
* 그러기 위해서는 일단 다 머지가 된 상태에서 하는게 나을 것 같아서 미루고 있습니다...
