### ISSUE TITLE
[BE] whoAmI 함수명 변경 및 리턴 타입 ID로 변경

### ISSUE THREAD

**Issue by moon9ua** [Trapscendence/ft_transcendence#56]
현재는 number(Int)를 리턴하고 있습니다.
함수명과 리턴 타입을 수정할 필요가 있다고 생각합니다..

또한 id가 db에서는 int로, 프론트와 백에서는 string, ID 등으로 혼용되고 있습니다.
이에 따라 sql 리턴값을 바로 사용하는 경우 오류가 발생하기도 했습니다.
논의가 필요할 것 같습니다.

**Comment by SeheonYu** [comment]
> 현재는 number(Int)를 리턴하고 있습니다.
> 함수명과 리턴 타입을 수정할 필요가 있다고 생각합니다..

리턴타입은 ID로 수정하겠습니당
함수명은 변경할 필요가 있는지는 모르겠는데 다른 이름 제안해주시면 수정할게요

> 또한 id가 db에서는 int로, 프론트와 백에서는 string, ID 등으로 혼용되고 있습니다.
> 이에 따라 sql 리턴값을 바로 사용하는 경우 오류가 발생하기도 했습니다.
> 논의가 필요할 것 같습니다.

DB에 ID가 serial로 저장돼야해서 int로 저장하고있고, string으로 저장하게되면 불필요한 쿼리가 많이 생기게돼서 DB 형식을 바꾸는건 힘들 것 같아요

**Comment by SeheonYu** [comment]
whoAmI 에서 getMyID로 수정할게요
