### ISSUE TITLE
[Channel/BE] Channel 모듈 필드명

### ISSUE THREAD

**Issue by moon9ua** [Trapscendence/ft_transcendence#58]
![image](https://user-images.githubusercontent.com/59914775/141607916-be0c9f42-fdbe-4061-b581-6bcf26f70fe5.png)

스네이크 케이스와 카멜 케이스가 통일이 안되어있는 상태입니다.

**Comment by SeheonYu** [comment]
lowerCamelCase로 바꿀게요

**Comment by moon9ua** [comment]
엇 저희 스네이크 케이스로 통일하는것같던데... 저는 상관없긴 합니다.

**Comment by SeheonYu** [comment]
스네이크로 바꿀게영

**Comment by SeheonYu** [comment]
채널에 남아있던 camelCase 필드를 snake_case로 수정했습니당

- `bannedUsers`, `mutedUsers` 를 `banned_users`, `muted_users` 로 바꿨어요
