### ISSUE TITLE
[FE] 우측 친구바 구현

### ISSUE THREAD

**Issue by seohee-choi** [Trapscendence/ft_transcendence#6]
- [ ] Drawer의 계패여부에 따라 함께 움직이는 화살표 구현
- drawer 옆에 길다랗고 투명한 막대(화살표를 담고 있음) 을 붙여서 drawer랑 함께 움직이게 하면 어떨까요?
  - css absolute 옵션을 써서 drawer랑 화살표박스를 붙여버리는 방법과
  - drawer보다 10px정도만 큰 박스를 만들고, drawer가 펼쳐져 있을 경우에만 이 상위박스를 visible하게 하는 방법 등이 있을듯.

- [ ] 친구 클릭시 메뉴

**Comment by seohee-choi** [comment]
2번을 현재 시도중이나 mui의 sx옵션 내에서 삼항연산자를 사용 하는 방법을 찾아보고 있습니다.

**Comment by moon9ua** [comment]
공통 컴포넌트 구현에 포함했습니다.
