### ISSUE TITLE
[Channel/BE] 방 비밀번호 암호화

### ISSUE THREAD

**Issue by SeheonYu** [Trapscendence/ft_transcendence#66]
> ## Security concerns
> Because you are creating a fully working website, there are a few security concerns that you will have to tackle
> - Any password stored in your database must be encrypted
> - ...

**Comment by evelon** [comment]
아이고 이런

**Comment by evelon** [comment]
그러고보니까 비밀번호 있을 때 방 들어가기를 안 했네요.

**Comment by SeheonYu** [comment]
악
