### ISSUE TITLE
[Channel/CM] Channel 남은 이슈 모음

### ISSUE THREAD

**Issue by moon9ua** [Trapscendence/ft_transcendence#70]
필수 항목만 적겠습니다.
개선하고자 하는 사항은 위키에 따로 적는걸로 합시다.

# CM
* [x] #95
* [x] #83 
* [x] #118

# FE
* [x] 밴 된 유저가 방 입장시 발생하는 에러 핸들링 -> GraphQL 에러는 `errorPolicy` 로 일차적으로 핸들링
* [x] 많이 보냈을 때의 413 에러 프론트에서 방지 -> input 500글자로 제한
* [x] 네트워크 에러 핸들링 (413 등의 네트워크 에러는 어떻게 핸들링하는지 아직 모르겠다.) -> mutation의 경우 try-catch 문으로... query는 아직 정확히 모르겠다.
* [x] admin 설정 기능
* [x] #96 

# BE
* [x] 채널에서 나갈 때 자동으로 양도할 수 있는 기능
- owner가 user에게 admin 권한을 부여하는 기능
  - [x] `delegateUserOnChannel`: 권한 부여
  - [x] `relegateUserOnChannel`: 권한 삭제  
* [x] #58  
* [x] #66
* [x] #76 
* [x] #81 
* [x] #94 
* [x] #134

**Comment by SeheonYu** [comment]
- #66

**Comment by SeheonYu** [comment]
> Unhandled Rejection (Error): Response not successful: Received status code 413
ApolloError
/src/errors/index.ts:54
  51 | // Constructs an instance of ApolloError given a GraphQLError
  52 | // or a network error. Note that one of these has to be a valid
  53 | // value or the constructed error will be meaningless.
  \> 54 | constructor({
     | ^  55 |   graphQLErrors,
  56 |   clientErrors,
  57 |   networkError,

**Comment by SeheonYu** [comment]
> 변경시 subscription 보내도록 구현해주세요! -gmoon

넹

**Comment by SeheonYu** [comment]
뮤트는 프론트에서 시간 처리 하는건가요??
