### ISSUE TITLE
[Migration/CM] 마이그레이션 기록을 읽지 못하여 나오는 오류

### ISSUE THREAD

**Issue by evelon** [Trapscendence/ft_transcendence#79]
빨리 해결해야합니다.

**Comment by evelon** [comment]
마이그레이션 파일을 한 번 추가했다가 삭제하면 고쳐집니다. db-migrate의 일시적인 오류인 듯 합니다.

**Comment by moon9ua** [comment]
저는 아직 해결되지 않았습니다 😞 
따라서 migration 폴더의 entrypoint.sh를 다음과 같이 수정했습니다.
![image](https://user-images.githubusercontent.com/59914775/141998064-8ba43ff4-f573-4ee3-be22-e6024798e78a.png)
migrate 오류시 재시도하지 않습니다.
