### ISSUE TITLE
[DM/CM] DM 개선하면 좋을 점들

### ISSUE THREAD

**Issue by moon9ua** [Trapscendence/ft_transcendence#87]
* 메세지 전송하고 input 비우기
* ~깜빡임 개선~
* ~(spa에 저해된다면) createUser시 subscription으로 데이터 받기 혹은 polling으로 갱신하기~

필수 사항이 아닌 것은 위키에 적도록 하겠습니다!

**Comment by seohee-choi** [comment]
이거 wiki에도 있어요

**Comment by SeheonYu** [comment]
#91

**Comment by SeheonYu** [comment]
- #87
