### ISSUE TITLE
[DM/CM] 최신 체크데이트 문제 해결하기

### ISSUE THREAD

**Issue by evelon** [Trapscendence/ft_transcendence#89]
현재는 getDM에서만 체크하도록 되어있는데, 이걸 메시지 받은 걸 볼 때마다 하도록 해야함.
이를 위해서는 프론트에서 새로운 메시지를 출력할 때 체크 데이트 mutation을 보내는 것으로 하는게 좋다고 생각함.

**Comment by seohee-choi** [comment]
네 좋습니다. 나중에 시간이 되면 해결하겠습니다.

**Comment by evelon** [comment]
해결 됐나요! updateCheckdate 뮤테이션을 인자 없이 보내면 됩니다.

**Comment by evelon** [comment]
해결됨.
