### ISSUE TITLE
[DM/CM] DM subscribe 하나로 줄일 수 있을까?

### ISSUE THREAD

**Issue by evelon** [Trapscendence/ft_transcendence#91]
DM user 목록과 메시지를 하나의 subscribe로 해결할 수 있을까요?
논의가 필요해보입니다.

**Comment by SeheonYu** [comment]
#87

**Comment by seohee-choi** [comment]
user를 따로 안불러오고 신규 message만 불러오면
신규 message의 유저값을 프론트가 따서 유저목록을 출력하면 어떨까요
단, 이 경우 메시지가 유저값을 담고있어야합니다.

**Comment by evelon** [comment]
하지 않기로 결정났음.
