### ISSUE TITLE
[Common/FE] unsubscribe

### ISSUE THREAD

**Issue by SeheonYu** [Trapscendence/ft_transcendence#98]
[Unsubscribe subscription in Apollo Client](https://stackoverflow.com/questions/51477002/unsubscribe-subscription-in-apollo-client)

> client.subscribe({ ...  }).subscribe({ ... }) will return an instance for your subscription, that you can use to unsubscribe.

```
componentDidMount () {
  // Setup subscription listener
  // (...)
  this.querySubscription = client.subscribe({
    // (...)
  }).subscribe({
    // (...)
  })
}

componentWillUnmount () {
  // Unsibscribe subscription
  this.querySubscription.unsubscribe();
}
```

**Comment by moon9ua** [comment]
> Yes, unsubscribe will be called automatically when the component unmounts. This also goes for subscribeToMore subscriptions as well.

컴포넌트가 언마운트되면 자동으로 cleanup 되는 것 같습니다.
